package AutoWiring.WithAnnotation;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Main {
    public static void main(String[] args) {
        ApplicationContext applicationContext = new AnnotationConfigApplicationContext(AppConfig.class);
        /**
         * The bean name getBean("employee") is automatically generated by spring by changing the first alphabet of
         * the class name to a small letter. If you need a custom name you can specify the name in front of the
         * @Component annotation. E.g:
         * @Component("myEmployee").
         * **/
        Employee emp = (Employee) applicationContext.getBean("employee");
        System.out.println(emp.toString());

        System.out.println("\n");

        Manager manager = applicationContext.getBean(Manager.class);
        manager.showStaffDetails();
    }
}
